'use client';

import Link from 'next/link';
import { Suspense, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';

export default function SignInPage() { return <main className="min-h-screen bg-[#f5f8fc] p-4 md:p-8"><div className="mx-auto grid min-h-[calc(100vh-4rem)] max-w-6xl overflow-hidden rounded-3xl bg-white shadow-2xl shadow-blue-950/10 lg:grid-cols-2"><section className="hidden bg-[#071b3a] p-12 text-white lg:block"><Link href="/" className="flex items-center gap-3 text-white no-underline"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-400 font-black text-[#071b3a]">GT</span><span><strong className="block tracking-wide">GLOBAL TRUST</strong><span className="text-xs tracking-[.22em] text-blue-100">BANK</span></span></Link><div className="mt-28"><p className="text-sm font-bold uppercase tracking-[.2em] text-emerald-300">Trusted banking demo</p><h1 className="mt-5 text-4xl font-black leading-tight">Welcome back to Global Trust Bank.</h1><p className="mt-5 max-w-md leading-7 text-blue-100">Access your account overview, virtual card, simulated transfers, investments, and loan tools.</p></div><div className="mt-28 rounded-2xl border border-white/10 bg-white/5 p-5 text-sm text-blue-100"><span className="font-bold text-emerald-300">DEMO NOTICE</span><p className="mt-2">No real money is stored, moved, or received in this application.</p></div></section><section className="flex items-center p-7 sm:p-12"><Suspense fallback={<p className="text-[#61708a]">Loading sign in...</p>}><SignInForm /></Suspense></section></div></main>; }

function SignInForm() {
  const router = useRouter(); const searchParams = useSearchParams(); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setError(null); const form = e.currentTarget; const data = { email: (form.elements.namedItem('email') as HTMLInputElement).value, password: (form.elements.namedItem('password') as HTMLInputElement).value }; try { const res = await fetch('/api/auth/signin', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const json = await res.json(); if (!res.ok) throw new Error(json.error || 'Sign in failed'); router.push(json.role === 'ADMIN' ? '/admin' : '/dashboard'); } catch (err) { setError(err instanceof Error ? err.message : 'Sign in failed'); setLoading(false); } }
  return <div className="w-full max-w-md"><Link href="/" className="text-sm font-bold text-[#0b5fff]">← Back to Global Trust Bank</Link><h2 className="mt-7 text-3xl font-black text-[#071b3a]">Sign in to your account</h2><p className="mt-2 text-sm text-[#61708a]">Enter your details to continue securely.</p>{searchParams.get('registered') && <p className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">Account request submitted. An administrator must approve it before full access.</p>}{error && <p className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form onSubmit={handleSubmit} className="mt-7 space-y-5"><label className="block text-sm font-bold text-[#10233f]">Email address<input className="gtb-input" name="email" type="email" required placeholder="you@example.com" /></label><label className="block text-sm font-bold text-[#10233f]">Password<input className="gtb-input" name="password" type="password" required placeholder="Enter your password" /></label><button className="gtb-btn-primary w-full" disabled={loading}>{loading ? 'Signing in...' : 'Sign in securely'}</button></form><p className="mt-6 text-center text-sm text-[#61708a]">New to Global Trust Bank? <Link className="font-bold text-[#0b5fff]" href="/auth/register">Open an account</Link></p></div>;
}
